[package]
name = "starsign"
version = "0.4.0"
description = "A multi-signature contract for StarkNet"
homepage = "https://github.com/eqlabs/starknet-multisig"

[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test --starknet ."
# Add your own custom commands and run them with scarb run <command>

# Uncomment if you want to use dependencies
# Note: currently testing doesn't work with dependencies
[dependencies]
starknet = ">=1.0.0"

[[target.starknet-contract]]
sierra = true
casm = true
# pythonic hints are necessary for cairo-lang to parse the casm file:
# Unsupported compiled class format. Cairo 1.0 compiled class must contain the attribute `pythonic_hints`.
casm-add-pythonic-hints = true